-- ============================================================================
--  DOMAIN INTELLIGENCE — initialisation / enrichissement de la base Supabase
--  À exécuter dans Supabase : SQL Editor → New query → coller → Run
--  Réexécutable sans erreur : il s'adapte à une table déjà existante.
--
--  Deux cas possibles :
--   * la table n'existe pas  -> elle est créée complète (section 1)
--   * la table existe déjà   -> les colonnes manquantes sont ajoutées (section 2)
--
--  L'application fonctionne dans les deux cas : si une colonne manque, elle est
--  simplement ignorée à l'enregistrement (voir _insert_adaptive dans db.py).
--  Exécuter ce script permet donc d'enregistrer la fiche complète.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Création de la table (projet neuf)
--    Reprend exactement les colonnes de l'énoncé : Domain, Registrar, Country,
--    IP, Domain age, Risk, Analyse effectuée le.
-- ----------------------------------------------------------------------------
create table if not exists public.domain_analyses (
    id               bigint generated by default as identity primary key,
    domain           text        not null,
    registrar        text,
    country          text,
    ip               text,
    domain_age_days  integer,
    risk             text        not null check (risk in ('LOW', 'MEDIUM', 'HIGH')),
    analyzed_at      timestamptz not null default now()
);

comment on table public.domain_analyses is
    'Analyses de fiabilité de noms de domaine produites par Domain Intelligence.';


-- ----------------------------------------------------------------------------
-- 2. Enrichissement : ajout des colonnes complémentaires si la table existe
--    déjà (typiquement la table minimale créée au début du projet).
--    ADD COLUMN IF NOT EXISTS est sans effet si la colonne est déjà là.
-- ----------------------------------------------------------------------------
alter table public.domain_analyses add column if not exists risk_score      integer;
alter table public.domain_analyses add column if not exists tld             text;
alter table public.domain_analyses add column if not exists asn             text;
alter table public.domain_analyses add column if not exists isp             text;
alter table public.domain_analyses add column if not exists https_ok        boolean;
alter table public.domain_analyses add column if not exists created_at_domain timestamptz;
alter table public.domain_analyses add column if not exists expires_at      timestamptz;
alter table public.domain_analyses add column if not exists risk_summary    text;

-- Colonnes JSON : la fiche complète et le détail du score
alter table public.domain_analyses add column if not exists risk_factors    jsonb;
alter table public.domain_analyses add column if not exists payload         jsonb;

comment on column public.domain_analyses.risk_factors is
    'Détail du score : liste de {label, points, detail}.';
comment on column public.domain_analyses.payload is
    'Fiche complète : infrastructure, DNS, certificat TLS, erreurs éventuelles.';


-- ----------------------------------------------------------------------------
-- 3. Index (recherche par domaine, tri chronologique)
-- ----------------------------------------------------------------------------
create index if not exists domain_analyses_analyzed_at_idx
    on public.domain_analyses (analyzed_at desc);
create index if not exists domain_analyses_domain_idx
    on public.domain_analyses (lower(domain));


-- ----------------------------------------------------------------------------
-- 4. Sécurité (RLS)
--    Politiques volontairement ouvertes : projet pédagogique mono-utilisateur
--    utilisant la clé « anon ».
--    En production : restreindre à « authenticated » et ajouter une colonne
--    user_id pour qu'un utilisateur ne voie que ses propres analyses.
-- ----------------------------------------------------------------------------
alter table public.domain_analyses enable row level security;

drop policy if exists "domain_analyses_lecture"     on public.domain_analyses;
drop policy if exists "domain_analyses_insertion"   on public.domain_analyses;
drop policy if exists "domain_analyses_suppression" on public.domain_analyses;

create policy "domain_analyses_lecture"
    on public.domain_analyses for select
    to anon, authenticated
    using (true);

create policy "domain_analyses_insertion"
    on public.domain_analyses for insert
    to anon, authenticated
    with check (true);

create policy "domain_analyses_suppression"
    on public.domain_analyses for delete
    to anon, authenticated
    using (true);


-- ----------------------------------------------------------------------------
-- 5. Vérification — liste les colonnes réellement présentes après exécution
-- ----------------------------------------------------------------------------
select column_name, data_type
from information_schema.columns
where table_schema = 'public' and table_name = 'domain_analyses'
order by ordinal_position;


-- ----------------------------------------------------------------------------
-- 6. Remise à zéro (décommenter si besoin)
-- ----------------------------------------------------------------------------
-- truncate table public.domain_analyses restart identity;
